version: "3.3"
services:
  nodejs_admin:
    restart: always
    build: 
      context: ./adminAPI
      dockerfile: Dockerfile
    networks:
      - frontend
    volumes:
      - ./www/:/var/www/html/admin_api/
    ports:
      - "30001:9000"
    extra_hosts:
      - "localhost:127.0.0.1"
    depends_on: 
      - nodejs_gold
    container_name: admin-api


  react_admin:
    restart: always
    build: 
      context: ./adminDash
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:30001 
    ports:
      - '3005:80'
    networks:
      - frontend
    depends_on: 
      - nodejs_admin
    container_name: admin_dash

networks:
  frontend:

volumes:
  my-datavolume-gold:
    