version: "3.3"
services:
  #admin API
  nodejs_admin:
    restart: always
    build: 
      context: ./adminAPI
      dockerfile: Dockerfile
    networks:
      - frontend
    volumes:
      - ./www/:/var/www/html/admin_api/
    ports:
      - "30001:9000"
    extra_hosts:
      - "localhost:127.0.0.1"
    container_name: admin-api

  #admin dashboard
  react_admin:
    restart: always
    build: 
      context: ./adminDash
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:30001 # admin api path
        - REACT_APP_INSIGHT_PLATFORM=AZURE,AWS,GCP
        - REACT_APP_WEBSITE_SUBTYPE=Admin1
    ports:
      - '3005:80'
    networks:
      - frontend
    depends_on: 
      - nodejs_admin
    container_name: admin_dash
 
networks:
  frontend:

volumes:
  my-datavolume-gold:
    
